# overlays/dev/patch.yaml


apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: my-app-container
          image: my-app-image:dev
          env:
            - name: DEBUG
              value: "true"
