   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: example-app
     namespace: default
   spec:
     replicas: 2
     selector:
       matchLabels:
         app: example-app
     template:
       metadata:
         labels:
           app: example-app
       spec:
         containers:
         - name: example-app
           image: hashicorp/http-echo
           args:
           - "-text=hello world"
           ports:
           - containerPort: 5678