# overlays/production/patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-app-container
          image: my-app-image:prod
          env:
            - name: LOG_LEVEL
              value: "ERROR"
