   apiVersion: networking.k8s.io/v1
   kind: Ingress
   metadata:
     name: example-app-ingress
     namespace: default
     annotations:
       nginx.ingress.kubernetes.io/rewrite-target: /
   spec:
     rules:
     - host: example.test
       http:
         paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: example-app-service
               port:
                 number: 80

#   kubectl apply -f app-deployment.yaml
#   kubectl apply -f app-service.yaml
#   kubectl apply -f app-ingress.yaml