apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-example-app
  namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-example-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-example-app
    spec:
      containers:
        - name: {{ .Release.Name }}-example-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - "-text={{ .Values.echoText }}"
          ports:
            - containerPort: 5678