apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: default
  labels:
    app: mywebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
#
  template:
    metadata:
      labels:
        app: mywebapp
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: hassannader2040/hasan-api
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: myconfigmap-part1
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"    # 50 milli cores (1/20 CPU)
          limits:
            memory: "128Mi" # 128 mebibytes
            cpu: "100m"