kind: ConfigMap
apiVersion: v1
metadata:
  name: myconfigmap-part1
  namespace: default
data:
  BG_COLOR: '#12181b'
  FONT_COLOR: '#FFFFFF'

#---
#kind: ConfigMap
#apiVersion: v1
#metadata:
#  name: myconfigmap-part2
#  namespace: default
#data:
#  CUSTOM_HEADER: 'Customized with a configmap!'
