apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1","meta.helm.sh/release-name":"mywebapp-release","meta.helm.sh/release-namespace":"default"},"creationTimestamp":"2024-11-28T22:08:30Z","generation":1,"labels":{"app":"mywebapp","app.kubernetes.io/managed-by":"Helm"},"name":"mydeployment","namespace":"default","resourceVersion":"2793896","uid":"6d216548-f7ab-4930-a9d6-c1924294009b"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"mywebapp"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"mywebapp"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"myconfigmap-part1"}}],"image":"devopsjourney1/mywebapp:latest","imagePullPolicy":"Always","name":"mycontainer","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{"limits":{"cpu":"100m","memory":"128Mi"},"requests":{"cpu":"50m","memory":"16Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2024-11-28T22:08:30Z","lastUpdateTime":"2024-11-28T22:08:50Z","message":"ReplicaSet \"mydeployment-747564f6ff\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2024-12-14T21:44:46Z","lastUpdateTime":"2024-12-14T21:44:46Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"readyReplicas":2,"replicas":2,"updatedReplicas":2}}
    meta.helm.sh/release-name: mywebapp-release
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-12-15T20:25:52Z"
  generation: 1
  labels:
    app: mywebapp
    app.kubernetes.io/managed-by: Helm
  name: mydeployment
  namespace: default
  resourceVersion: "1822"
  uid: a82e6636-c33e-4f99-816c-aebbbefacbf3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mywebapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mywebapp
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: myconfigmap-part1
        image: hassannader2040/hasan-api
        imagePullPolicy: Always
        name: mycontainer
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 16Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-12-15T20:25:52Z"
    lastUpdateTime: "2024-12-15T20:25:52Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-12-15T20:35:53Z"
    lastUpdateTime: "2024-12-15T20:35:53Z"
    message: ReplicaSet "mydeployment-747564f6ff" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
