replicaCount: 2

image:
  repository: hashicorp/http-echo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

configmap:
  myKey: "Hello, World!"

env:
  name: MY_ENV_VAR
  valueFrom:
    configMapKeyRef:
      name: my-configmap
      key: myKey