# overlays/staging/patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-app-container
          image: my-app-image:staging
          env:
            - name: LOG_LEVEL
              value: "DEBUG"
# if the container was created or not
# generating the staging and how to make sure if it works or not
# generating the stages

