name: phase2_CI/CD Pipeline pushing to docker hub

on:
  push:
    branches:
      - master
    # paths:
    #   - 'phase3/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: List project files (Optional step to check the file structure)
      - name: List project files
        run: ls -la phase3/

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t hasannader2040/hasan-api:temperature-app -f phase3/Dockerfile .

      # Step 4: Log in to Docker Hub using a command
      - name: Log in to Docker Hub
        run: |
          docker login -u hassannader2040 -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push hasannader2040/hasan-api:temperature-app