name: phase2_CI/CD Pipeline pushing to docker hub 

on:
  push:
    branches:
      - master
    # paths:
    #   - 'phase2/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build the Docker image
      - name: Build Docker image
        run: docker build -t hasan2040/hasan-api:temperature-app -f phase3/Dockerfile .

      # Step 3: Log in to Docker Hub using GitHub Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push hasan2040/hasan-api:temperature-app
# fixing /bin/sh -c pip3 install no-cache-dir and their dependencies