name: phase2_CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'phase2/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t hasan2040/hasan-api:temperature-app -f phase3/Dockerfile .


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push hasan/hasan-api:temperature-app
